### ISSUE TITLE
currentTest.fullTitle() always return same title

### ISSUE THREAD

**Issue by asafbenm** [PinkyJie/cypress-auto-stub-example#26]
the full title it's always the same one. (save in file all under the first full title)
you can try to reproduce it by running more then one "it" statements in one spec

it's seems that you need to use for example:
const currentTestFullTitle = (Cypress as any).mocha.getRunner().suite.ctx.currentTest.fullTitle();
and not 
(Cypress as any).mocha._mocha.suite.suites[0].tests[0].fullTitle();; 
in test-info.ts file

**Comment by PinkyJie** [comment]
Thanks for raising the issue, fixed.
